server:
  port: 8898
spring:
  application:
    name: effectivebankingservice
  config:
    import: classpath:secret-settings.yml
  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${POSTGRES_SCHEMA}
jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_EXPIRATION}

