JWT_SECRET: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
JWT_EXPIRATION: 10m

POSTGRES_JDBC_URL: jdbc:postgresql://localhost:5432/pg_effectiveBankingService_db
POSTGRES_USERNAME: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_SCHEMA: public
SHOW_SQL: true
